language: java
sudo: false
install: true

#addons:
#  sonarcloud:
#    organization: "rsynek-github"
#    token:
#      secure: $SONARCLOUD_TOKEN

jdk:
- oraclejdk8
script:
- mvn --quiet clean install -Prun-code-coverage
#- mvn --quiet jacoco:report jacoco:merge sonar:sonar -Preport-code-coverage
- |
  if [$TRAVIS_EVENT_TYPE == "pull_request"]; then
    echo pull request
  else
    echo branch
  fi

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"