language: java
sudo: false
install: true

#addons:
#  sonarcloud:
#    organization: "rsynek-github"
#    token:
#      secure: $SONARCLOUD_TOKEN

jdk:
- oraclejdk8
script:
- mvn --quiet clean install -Prun-code-coverage
#- mvn --quiet jacoco:report jacoco:merge sonar:sonar -Preport-code-coverage
- |
  if [$TRAVIS_EVENT_TYPE == "pull_request"]; then
    mvn --quiet jacoco:report jacoco:merge sonar:sonar -Preport-code-coverage -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=rsynek-github -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.projectKey=rsynek_sonarcloud-playground -Dsonar.pullrequest.base=$TRAVIS_BRANCH -Dsonar.pullrequest.branch=$TRAVIS_PULL_REQUEST_BRANCH -Dsonar.pullrequest.key=$TRAVIS_PULL_REQUEST -Dsonar.pullrequest.provider=GitHub -Dsonar.pullrequest.github.repository=$TRAVIS_PULL_REQUEST_SLUG
  else
    mvn --quiet jacoco:report jacoco:merge sonar:sonar -Preport-code-coverage -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=rsynek-github -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.projectKey=rsynek_sonarcloud-playground
  fi

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"